### ISSUE TITLE
Is the "Comparing Functions" example correct?

### ISSUE THREAD

**Issue by slanden** [bheisler/criterion.rs#566]
I just started learning Criterion, and I copied the  ["Comparing Functions" example](https://bheisler.github.io/criterion.rs/book/user_guide/comparing_functions.html) and ran it twice. The results say that `fibonacci_slow()` is much faster (~266.94 **ps**) than `fibonacci_fast()` (~5.05 **ns**). Is anyone able to reproduce similar results?

- intel Core i7-8550U CPU @ 1.80GHz × 8
- Rust 1.59, 2021 Edition
- Criterion 0.3

**Update:**

I wrapped the inputs to each of the Fibonacci functions in `black_box()`, 

```
fibonacci_slow(black_box(*i))
```

which made the results from`fibonacci_slow()` and `fibonacci_fast()` match their expected speeds. That made me wonder about the following [excerpt from the docs](https://bheisler.github.io/criterion.rs/book/faq.html#when-should-i-use-criterionblack_box).
> if you use parameterized benchmarks, the parameters are automatically black-boxed by Criterion.rs so you don't need to do anything. If you're writing an un-parameterized benchmark of a function that takes an argument, however, this may be worth considering.

Is the example perhaps relying on this automatic black-boxing, and it's not actually doing it in this case?

**Comment by bheisler** [comment]
Hello!

Good catch! You're right, I missed a `black_box` there.

**Comment by bheisler** [comment]
I've pushed a fix for this to the branch for the next version.

**Comment by dclong** [comment]
If there anyway to make `black_box` applied automatically? If the authors overlooks it sometimes, I imagine it will be a common issue among users.

**Comment by bheisler** [comment]
Well, aside from using Criterion's built-in parameterized-benchmarking tools, no. I'm not sure that inserting `black_box` automatically would be desirable in any but the simplest cases anyway, since an automated system couldn't have the author's knowledge of what exactly it is they're trying to measure.

**Comment by slanden** [comment]
I just got around to trying out the Fibonacci example (copy & pasted word for word) with v0.4 and I still get about the same results as originally posted.

Update: I just realized the example didn't have `black_box()` in either function call. I don't recall, but maybe instead of adding the missing `black_box()`, the one that was there was removed?
